all:
  hosts:
    node1:
      ansible_host: 10.3.52.55
      ip: 10.3.52.55
      access_ip: 10.3.52.55
    node2:
      ansible_host: 10.3.53.27
      ip: 10.3.53.27
      access_ip: 10.3.53.27
    node3:
      ansible_host: 10.3.53.118
      ip: 10.3.53.118
      access_ip: 10.3.53.118
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
